FORMAT: 1A
HOST: http://http://ec2-35-160-66-173.us-west-2.compute.amazonaws.com:8080/pill_reminder-0.0.1-SNAPSHOT

# PillReminder

Pill Reminder is a simple API allowing consumers to view pills, categories and get reminders.

## Categories Collection [/categories]

### List All Categories [GET]

+ Response 200 (application/json)

        [
            {
                "categoryId": "1",
                "categoryName": "Vitamins"
            },
            {
                "categoryId": "2",
                "categoryName": "AntiBiotics"
            }
        ]

### Create a New Category [POST]

You may create your own category using this action. It takes a JSON
object containing name of the category.

+ Request (application/json)

        {
            "categoryName": "Vitamins",
        }

+ Response 201 (application/json)

    + Headers

            Location: /categories/1

    + Body

            {
                "categoryId": "1",
                "categoryName": "Vitamins"
            }
## Individual Category [/categories/{id}]

### Retrieve a specific Category [GET]

+ Response  200 (application/json)

        [
            {
                "categoryId": "1",
                "categoryName": "Vitamins"
            }
        ]

### Update a specific Category [PATCH]

+ Request (application/json)
        
        [
            {   
                "categoryId": "1",
                "categoryName": "Vitamins"
            }
        ]
+ Response 200 (OK)

### Delete a specific Category [DELETE]

+ Response 200 (OK)

##Retrieve all pills for specific category [/categories/{category_id}/pills]

+Response 200 (application/json)

        [
            {
                "pill_id": "1",
                "pill_name": "BComplex",
                "pill_category":"1"
            },
            {
                "pill_id": "2",
                "pill_name": "Zinc",
                "pill_category":"1"
            }
        ]

## Pills Collection [/pills]

### List All Pills [GET]

+ Response 200 (application/json)

        [
            {
                "id": "1",
                "name": "BComplex"
            }
        ]

### Create a New Pill [POST]

You may create your own pill using this action. It takes a JSON
object containing name and category of the pill.

+ Request (application/json)

        {
            "name": "Zinc",
            "category_id": "1"
        }

+ Response 201 (application/json)

    + Headers

            Location: /pills/1

    + Body

            {
                "id": "2",
                "name": "Zinc",
                "category_id": "1"
            }


## Individual Pill [/pills/{id}]

### Retrieve a specific Pill [GET]

+ Response 200 (application/json)

        [
            {
                "pill_id": "1",
                "pill_name": "BComplex",
                "pill_category":"1"
            }
        ]

### Update a specific Pill [PATCH]

+ Request (application/json)

        [
            {
                "pill_id": "1",
                "pill_name": "Zinc",
                "pill_category":"1"
            }
        ]
+ Response 200 (OK)

### Delete a specific Pill [DELETE]

+ Response 200 (OK)

##Alternatives [/pills/{id}/alternatives]

### Retrieve all alternative pills for specific pill id [GET]

+ Response 200 (application/json)

        [
            {
                "pill_id": "1",
                "pill_name": "test",
                "pill_category":"1"
            }
        ]

## Individual User [/users/{id}]

### Retrieve a specific User [GET]

+ Response 200 (application/json)

        [
            {
                "user_id": "1",
                "user_name": "Satya",
                "user_email": "satyapriya.g@gmail.com",
                "user_contact":"9999999999"
            }
        ]
## Individual Alarm [/alarms/{id}]

### Retrieve a specific Category [GET]

+ Response  200 (application/json)

        [
            {
              "aid": 14,
              "apillId": 3,
              "arecurrence": 1,
              "auserId": 1,
              "astartDate": "2016-10-28",
              "aendDate": "2016-10-31",
              "apillName": "B-12 Complex",
              "acategoryId": 3
            }
        ]

### Update a specific Alarm [PATCH]

+ Response 200 (OK)

### Delete a specific Alarm [DELETE]

+ Response 200 (OK)

## Alarms [/users/{id}/alarms]

### Retrieve all alarms for specific User [GET]

+ Response 200 (application/json)

        [
            
              {
                "aid": 14,
                "apillId": 3,
                "arecurrence": 1,
                "auserId": 1,
                "astartDate": "2016-10-28",
                "aendDate": "2016-10-31",
                "apillName": "B-12 Complex",
                "acategoryId": 3
              },
              {
                "aid": 15,
                "apillId": 3,
                "arecurrence": 2,
                "auserId": 1,
                "astartDate": "2016-10-26",
                "aendDate": "2016-10-29",
                "apillName": "B-12 Complex",
                "acategoryId": 3
              }
        ]

## Alarms for current day [/users/{id}/today]

### Retrieve all alarms of specific User for today  [GET]


+ Response 200 (application/json)

        [
            
            {
            "aid": 19,
            "apillId": 4,
            "arecurrence": 1,
            "auserId": 144,
            "astartDate": "2016-10-22",
            "aendDate": "2016-11-05",
            "apillName": "test",
            "acategoryId": 3
            },
            {
            "aid": 20,
            "apillId": 5,
            "arecurrence": 1,
            "auserId": 144,
            "astartDate": "2016-10-29",
            "aendDate": "2016-11-05",
            "apillName": "test edit",
            "acategoryId": 4
            },
            {
            "aid": 29,
            "apillId": 126,
            "arecurrence": 4,
            "auserId": 144,
            "astartDate": "2016-10-28",
            "aendDate": "2016-11-05",
            "apillName": "add pill test",
            "acategoryId": 127
           }
        ]