package pills.entity;
// Generated Oct 18, 2016 1:47:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pill generated by hbm2java
 */
@Entity
@Table(name="pill"
    ,catalog="pillreminder"
)
public class Pill  implements java.io.Serializable {


     private Integer pillId;
     private Category category;
     private String pillName;
     private Set<Alarm> alarms = new HashSet<Alarm>(0);
     //private Set<Pill> pillsForAlternatePillId = new HashSet<Pill>(0);
     //private Set<Pill> pillsForPillId = new HashSet<Pill>(0);

    public Pill() {
    }

	public Pill(String pillName){
		this.pillName = pillName;
	}
	public Pill(Integer pillId){
		this.pillId = pillId;
	}
    public Pill(Category category, String pillName) {
        this.category = category;
        this.pillName = pillName;
    }
    public Pill(Category category, String pillName, Set<Alarm> alarms, Set<Pill> pillsForAlternatePillId, Set<Pill> pillsForPillId) {
       this.category = category;
       this.pillName = pillName;
       this.alarms = alarms;
//       this.pillsForAlternatePillId = pillsForAlternatePillId;
//       this.pillsForPillId = pillsForPillId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pill_id", unique=true, nullable=false)
    public Integer getPillId() {
        return this.pillId;
    }
    
    public void setPillId(Integer pillId) {
        this.pillId = pillId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pill_category_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="pill_name", nullable=false, length=30)
    public String getPillName() {
        return this.pillName;
    }
    
    public void setPillName(String pillName) {
        this.pillName = pillName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pill")
    public Set<Alarm> getAlarms() {
        return this.alarms;
    }
    
    public void setAlarms(Set<Alarm> alarms) {
        this.alarms = alarms;
    }

/*@ManyToMany(fetch=FetchType.LAZY, mappedBy="pillsForPillId")
    public Set<Pill> getPillsForAlternatePillId() {
        return this.pillsForAlternatePillId;
    }
    
    public void setPillsForAlternatePillId(Set<Pill> pillsForAlternatePillId) {
        this.pillsForAlternatePillId = pillsForAlternatePillId;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="pillsForAlternatePillId")
    public Set<Pill> getPillsForPillId() {
        return this.pillsForPillId;
    }
    
    public void setPillsForPillId(Set<Pill> pillsForPillId) {
        this.pillsForPillId = pillsForPillId;
    }
*/



}


