package pills.entity;
// Generated Oct 18, 2016 11:30:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="pillreminder"
)
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String userEmail;
     private Integer userContact;
     private Set<UserRole> userRoles = new HashSet<UserRole>(0);
     private Set<Alarm> alarms = new HashSet<Alarm>(0);

    public User() {
    }

	
    public User(String userName, String userEmail) {
        this.userName = userName;
        this.userEmail = userEmail;
    }
    public User(String userName, String userEmail, Integer userContact, Set<UserRole> userRoles, Set<Alarm> alarms) {
       this.userName = userName;
       this.userEmail = userEmail;
       this.userContact = userContact;
       this.userRoles = userRoles;
       this.alarms = alarms;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="user_name", nullable=false, length=30)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="user_email", nullable=false, length=30)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="user_contact")
    public Integer getUserContact() {
        return this.userContact;
    }
    
    public void setUserContact(Integer userContact) {
        this.userContact = userContact;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<UserRole> getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Alarm> getAlarms() {
        return this.alarms;
    }
    
    public void setAlarms(Set<Alarm> alarms) {
        this.alarms = alarms;
    }




}


